### ISSUE TITLE
TypeError: numpy boolean subtract, the `-` operator, is deprecated,

### ISSUE THREAD

**Issue by passdan** [zyndagj/reptiming_logFC#5]
I am having an error occur when running the script, full message below and I'm unsure if it is actually a version error or something with my data input. If there is a change to numpy calling, I haven't been able to solve what needs to be changed, but if there is a line that needs to be updated, can anyone advise?

```
repliscan.py -r ~/Projects/REFDB/TAIR10_Chr.fasta --plot repliscan_info.txt
Making 1000bp window bed from FAI
Converting bam to bed
Converting bed to bedgraph
Aggregating replicates
Merging with sum
- uniq_bams/ARO5_uniq.bedgraph
- uniq_bams/ARO6_uniq.bedgraph
Normalizing signals using Coverage
Making LogFold Files From: ['G1_norm.bedgraph', 'ES1_norm.bedgraph', 'ES2_norm.bedgraph', 'LS1_norm.bedgraph', 'LS2_norm.bedgraph']
Making ES1_ratio.bedgraph
Making ES2_ratio.bedgraph
Making LS1_ratio.bedgraph
Making LS2_ratio.bedgraph
Smoothing: ['ES1_ratio.bedgraph', 'ES2_ratio.bedgraph', 'LS1_ratio.bedgraph', 'LS2_ratio.bedgraph']
Parsing : ['ES1_ratio_3.smooth.bedgraph', 'ES2_ratio_3.smooth.bedgraph', 'LS1_ratio_3.smooth.bedgraph', 'LS2_ratio_3.smooth.bedgraph']
Calculating thresholds...
Using a threshold of 0.76 for chromosome Chr1
Traceback (most recent call last):
  File "/home/sbi6dap/.local/bin/repliscan.py", line 1007, in <module>
    main()
  File "/home/sbi6dap/.local/bin/repliscan.py", line 129, in main
    makeGFF(fList, chromDict, args.level, args.window, args.plot, args.threshold, args.scope, args.log, args.value, args.prep, args.classifier)
  File "/home/sbi6dap/.local/bin/repliscan.py", line 796, in makeGFF
    rBounds = calcRegionBounds(bMask)
  File "/home/sbi6dap/.local/bin/repliscan.py", line 996, in calcRegionBounds
    d = np.diff(counter)
  File "/home/sbi6dap/Local/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

```

Versions which I am using
```
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
>>> import numpy
>>> import scipy
>>> numpy.__version__
'1.13.0'
>>> scipy.__version__
'1.1.0'
```

**Comment by zyndagj** [comment]
Thanks for discovering this. I'll take a look at it today and figure out if I can make it future proof or just need a stricter numpy requirement.

**Comment by passdan** [comment]
Great. I can provide inputs if there is any issues with reproducibility.

**Comment by passdan** [comment]
Sorry, slip of the clicking finger

**Comment by passdan** [comment]
Hi Greg. I was wondering if you were able to find a fix for this issue?

**Comment by zyndagj** [comment]
I was able to replicate your issue

```
(repliscan) wireless-10-146-49-14:test gzynda$ repliscan.py -r TAIR10_Chr.all.fasta --plot input.txt 
Converting bam to bed
Converting bed to bedgraph
Aggregating replicates
Merging with sum
- E1.bedgraph
- E2.bedgraph
- E3.bedgraph
Merging with sum
- M1.bedgraph
- M2.bedgraph
- M3.bedgraph
Merging with sum
- L1.bedgraph
- L2.bedgraph
- L3.bedgraph
/Users/gzynda/miniconda3/envs/repliscan/lib/python2.7/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
Normalizing signals using Coverage
Making LogFold Files From: ['G1_norm.bedgraph', 'E_norm.bedgraph', 'M_norm.bedgraph', 'L_norm.bedgraph']
Making E_ratio.bedgraph
Making M_ratio.bedgraph
Making L_ratio.bedgraph
Smoothing: ['E_ratio.bedgraph', 'M_ratio.bedgraph', 'L_ratio.bedgraph']
Parsing : ['E_ratio_3.smooth.bedgraph', 'M_ratio_3.smooth.bedgraph', 'L_ratio_3.smooth.bedgraph']
Calculating thresholds...
Using a threshold of 0.92 for chromosome Chr1
Traceback (most recent call last):
  File "/Users/gzynda/miniconda3/envs/repliscan/bin/repliscan.py", line 1010, in <module>
    main()
  File "/Users/gzynda/miniconda3/envs/repliscan/bin/repliscan.py", line 129, in main
    makeGFF(fList, chromDict, args.level, args.window, args.plot, args.threshold, args.scope, args.log, args.value, args.prep, args.classifier)
  File "/Users/gzynda/miniconda3/envs/repliscan/bin/repliscan.py", line 799, in makeGFF
    rBounds = calcRegionBounds(bMask)
  File "/Users/gzynda/miniconda3/envs/repliscan/bin/repliscan.py", line 999, in calcRegionBounds
    d = np.diff(counter)
  File "/Users/gzynda/miniconda3/envs/repliscan/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

(repliscan) wireless-10-146-49-14:test gzynda$ conda list | grep numpy
numpy                     1.13.0                   py27_0  
```

It looks like this was a known issue with numpy

https://github.com/numpy/numpy/issues/9367

and works if you upgrade. The latest is 1.14, but 1.13.1 also works.

```
(repliscan) wireless-10-146-49-14:test gzynda$ repliscan.py -r TAIR10_Chr.all.fasta --plot input.txt 
Converting bam to bed
Converting bed to bedgraph
Aggregating replicates
Merging with sum
- E1.bedgraph
- E2.bedgraph
- E3.bedgraph
Merging with sum
- M1.bedgraph
- M2.bedgraph
- M3.bedgraph
Merging with sum
- L1.bedgraph
- L2.bedgraph
- L3.bedgraph
/Users/gzynda/miniconda3/envs/repliscan/lib/python2.7/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
Normalizing signals using Coverage
Making LogFold Files From: ['G1_norm.bedgraph', 'E_norm.bedgraph', 'M_norm.bedgraph', 'L_norm.bedgraph']
Making E_ratio.bedgraph
Making M_ratio.bedgraph
Making L_ratio.bedgraph
Smoothing: ['E_ratio.bedgraph', 'M_ratio.bedgraph', 'L_ratio.bedgraph']
Parsing : ['E_ratio_3.smooth.bedgraph', 'M_ratio_3.smooth.bedgraph', 'L_ratio_3.smooth.bedgraph']
Calculating thresholds...
Using a threshold of 0.92 for chromosome Chr1
Using a threshold of 0.95 for chromosome Chr2
Using a threshold of 0.93 for chromosome Chr3
Using a threshold of 0.94 for chromosome Chr4
Using a threshold of 0.93 for chromosome Chr5
Using a threshold of 1.00 for chromosome ChrC
Using a threshold of 1.50 for chromosome ChrM
Done
(repliscan) wireless-10-146-49-14:test gzynda$ conda list | grep numpy
numpy                     1.13.1           py27hd567e90_2  
```

**Comment by passdan** [comment]
Yep, works perfectly. Thanks for taking the time!
