### ISSUE TITLE
Repliscan installation error

### ISSUE THREAD

**Issue by Saddamhus** [zyndagj/reptiming_logFC#7]
Hello, I am trying to install repliscan on my Mac, but I am seeing this error. I am new to data analysis and can't figure out what does these errors mean. I would really appreciate your help.  
I have installed python 3.6 and pip pip 20.1.1 that I have upgraded to 20.2.2.

```
saddams-MBP:~ saddamhusain$ pip install --user git+https://github.com/zyndagj/repliscan.git
Collecting git+https://github.com/zyndagj/repliscan.git
  Cloning https://github.com/zyndagj/repliscan.git to /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k
  Running command git clone -q https://github.com/zyndagj/repliscan.git /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k
Building wheels for collected packages: repliscan
  Building wheel for repliscan (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-wheel-nm2vzbop
       cwd: /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/
  Complete output (48 lines):
  make: Nothing to be done for `all'.
  running bdist_wheel
  running build
  running build_scripts
  creating build
  creating build/scripts-3.6
  copying and adjusting repliscan.py -> build/scripts-3.6
  copying and adjusting RATrap.py -> build/scripts-3.6
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 390, in find_cookie
      line_string = line.decode('utf-8')
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py", line 21, in <module>
      scripts = ["repliscan.py","RATrap.py","wavelets"])
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
      self.copy_scripts()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
      encoding, lines = tokenize.detect_encoding(f.readline)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 431, in detect_encoding
      encoding = find_cookie(first)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 395, in find_cookie
      raise SyntaxError(msg)
  SyntaxError: invalid or missing encoding declaration for 'wavelets'
  ----------------------------------------
  ERROR: Failed building wheel for repliscan
  Running setup.py clean for repliscan
Failed to build repliscan
Installing collected packages: repliscan
    Running setup.py install for repliscan ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-record-a0fzkzj6/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/saddamhusain/Library/Python/3.6/include/python3.6m/repliscan
         cwd: /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/
    Complete output (50 lines):
    make: Nothing to be done for `all'.
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.6
    copying and adjusting repliscan.py -> build/scripts-3.6
    copying and adjusting RATrap.py -> build/scripts-3.6
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 390, in find_cookie
        line_string = line.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py", line 21, in <module>
        scripts = ["repliscan.py","RATrap.py","wavelets"])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
        self.copy_scripts()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
        encoding, lines = tokenize.detect_encoding(f.readline)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 431, in detect_encoding
        encoding = find_cookie(first)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 395, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: invalid or missing encoding declaration for 'wavelets'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-f56zjr9k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-record-a0fzkzj6/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/saddamhusain/Library/Python/3.6/include/python3.6m/repliscan Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -m pip install --upgrade pip' command.

```

**Comment by zyndagj** [comment]
It looks like you're missing the wavelets dependency. I can try deploying this on conda next week so the installation process will be much easier.

**Comment by Saddamhus** [comment]
Thanks a lot Zynda for your response. That would be a great help, meanwhile I will try installing wavelets.

**Comment by Saddamhus** [comment]
Hi, I have installed waveletsas with one warning message (warning: unused variable 'alwaysBeg' [-Wunused-variable]) and confirmed it through --help command but when I am installing repliscan I am having this error again. Could you please suggest how may I resolve this issue, I would appreciate that? and I am sorry for the huge message.

```
saddams-MBP:src saddamhusain$ ../bin/wavelets --help
wavelets
	[--boundary <string = periodic>]
	[--filter <string = LA8>]
	[--help (includes lots of info)]
	[--level <integer = 4>]
	[--operation <string = smooth>]
	[--prefix <string = ''>]
	[--to-stdout]
	[--version]
	<file-name>


	--level is the max level to compute to

	--prefix is added to front of each output file name

	--to-stdout applicable to --operation = scale|smooth

	Allowed --operation list:
		all
		details
		mra
		scale
		smooth
		wave
		wave-scale


	Allowed --filter list:
		Haar
		D4
		D6
		D8
		D10
		D12
		D14
		D16
		D18
		D20
		LA8
		LA10
		LA12
		LA14
		LA16
		LA18
		LA20
		BL14
		BL18
		BL20
		C6
		C12
		C18
		C24
		C30


	Allowed --boundary list:
		Reflected
		Periodic


	<file-name> may be '-' to indicate reading from stdin

saddams-MBP:src saddamhusain$ pip install --user git+https://github.com/zyndagj/repliscan.git
Collecting git+https://github.com/zyndagj/repliscan.git
  Cloning https://github.com/zyndagj/repliscan.git to /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9
Building wheels for collected packages: repliscan
  Building wheel for repliscan (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-wheel-rtxi9pjn
       cwd: /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/
  Complete output (48 lines):
  make: Nothing to be done for `all'.
  running bdist_wheel
  running build
  running build_scripts
  creating build
  creating build/scripts-3.6
  copying and adjusting repliscan.py -> build/scripts-3.6
  copying and adjusting RATrap.py -> build/scripts-3.6
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 390, in find_cookie
      line_string = line.decode('utf-8')
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py", line 21, in <module>
      scripts = ["repliscan.py","RATrap.py","wavelets"])
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
      self.copy_scripts()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
      encoding, lines = tokenize.detect_encoding(f.readline)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 431, in detect_encoding
      encoding = find_cookie(first)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 395, in find_cookie
      raise SyntaxError(msg)
  SyntaxError: invalid or missing encoding declaration for 'wavelets'
  ----------------------------------------
  ERROR: Failed building wheel for repliscan
  Running setup.py clean for repliscan
Failed to build repliscan
DEPRECATION: Could not build wheels for repliscan which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: repliscan
    Running setup.py install for repliscan ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-record-tm7iy_qo/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/saddamhusain/Library/Python/3.6/include/python3.6m/repliscan
         cwd: /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/
    Complete output (50 lines):
    make: Nothing to be done for `all'.
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.6
    copying and adjusting repliscan.py -> build/scripts-3.6
    copying and adjusting RATrap.py -> build/scripts-3.6
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 390, in find_cookie
        line_string = line.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py", line 21, in <module>
        scripts = ["repliscan.py","RATrap.py","wavelets"])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
        self.copy_scripts()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
        encoding, lines = tokenize.detect_encoding(f.readline)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 431, in detect_encoding
        encoding = find_cookie(first)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 395, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: invalid or missing encoding declaration for 'wavelets'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"'; __file__='"'"'/private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-req-build-ddru35_9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y4/d8ny96tj4lq95881n6qy5rw80000gn/T/pip-record-tm7iy_qo/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/saddamhusain/Library/Python/3.6/include/python3.6m/repliscan Check the logs for full command output.
saddams-MBP:src saddamhusain$

```
